# Generated by Django 4.2.15 on 2025-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0002_alter_job_iscreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='isCreated',
            new_name='isInitiated',
        ),
    ]
