# Generated by Django 4.2.15 on 2025-03-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0003_rename_iscreated_job_isinitiated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='taskGranularity',
            field=models.IntegerField(default=40),
        ),
    ]
