# Generated by Django 4.2.15 on 2025-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0004_alter_job_taskgranularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isInitiating',
            field=models.BooleanField(default=False),
        ),
    ]
