# Generated by Django 4.2.15 on 2025-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0005_job_isinitiating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='threads',
            field=models.IntegerField(default=4),
        ),
    ]
