# Generated by Django 4.2.15 on 2025-03-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0006_job_threads'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='currentRow',
            field=models.IntegerField(default=0),
        ),
    ]
