# Generated by Django 4.2.15 on 2025-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0007_task_currentrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='totRows',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
