# Generated by Django 4.2.15 on 2025-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0008_task_totrows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='fileURL',
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
