# Generated by Django 4.2.15 on 2025-03-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0009_remove_task_fileurl_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='completedFileUrl',
        ),
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
