# Generated by Django 4.2.15 on 2025-03-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_api', '0010_remove_job_completedfileurl_job_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.FileField(help_text='When the job is completed, calculate the file using the provided admin action', null=True, upload_to=''),
        ),
    ]
