# Generated by Django 4.2.15 on 2025-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0028_alter_iguser_unique_together_alter_iguser_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgcrop',
            name='suggestedText',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
