# Generated by Django 4.2.15 on 2025-03-10 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0029_imgcrop_suggestedtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False)),
                ('taskGranularity', models.IntegerField(default=40, editable=False)),
                ('completedFileUrl', models.CharField(blank=True, max_length=5000, null=True)),
                ('notes', models.CharField(blank=True, max_length=5000, null=True)),
                ('isCreated', models.BooleanField(default=True)),
                ('isWorking', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='JobIGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=300)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.job')),
            ],
            options={
                'unique_together': {('job', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progressiveID', models.IntegerField(editable=False)),
                ('inProgress', models.BooleanField()),
                ('isCompleted', models.BooleanField()),
                ('fileURL', models.CharField(blank=True, max_length=5000, null=True)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.job')),
            ],
            options={
                'unique_together': {('progressiveID', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(editable=False, max_length=500)),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.job')),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, to='storage_api.task')),
            ],
            options={
                'unique_together': {('job', 'content')},
            },
        ),
        migrations.CreateModel(
            name='JobUserHashtagUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(editable=False, max_length=5000)),
                ('hashtag', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.jobhashtag')),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.job')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='storage_api.jobiguser')),
            ],
            options={
                'unique_together': {('job', 'user', 'hashtag', 'image_path')},
            },
        ),
    ]
