# Generated by Django 4.2.15 on 2025-03-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0030_job_jobiguser_task_jobhashtag_jobuserhashtaguse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobhashtag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobhashtag',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobhashtag',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='jobiguser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobiguser',
            name='job',
        ),
        migrations.AlterUniqueTogether(
            name='jobuserhashtaguse',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobuserhashtaguse',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='jobuserhashtaguse',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobuserhashtaguse',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='task',
            name='job',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='JobHashtag',
        ),
        migrations.DeleteModel(
            name='JobIGUser',
        ),
        migrations.DeleteModel(
            name='JobUserHashtagUse',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
